# Generated by Django 3.0.6 on 2020-05-29 18:08

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beerboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerboard',
            name='img',
            field=django_fields.fields.DefaultStaticImageField(blank=True, null=True, upload_to='beerboard/'),
        ),
    ]
