# Generated by Django 3.0.6 on 2020-05-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerboard', '0002_auto_20200530_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerboard',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='beerboard/'),
        ),
    ]
