# Generated by Django 3.0.6 on 2020-05-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerboard', '0004_beerboardcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerboardcomment',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
