# Generated by Django 3.0.6 on 2020-05-31 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcomment',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='foodboard.FoodBoard'),
        ),
    ]
