# Generated by Django 3.0.6 on 2020-05-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodboard',
            name='recommend',
        ),
        migrations.RemoveField(
            model_name='foodboard',
            name='reply',
        ),
    ]
